services:
  postgres-db:
    image: postgres:17-alpine
    container_name: local-postgres-db
    environment:
      POSTGRES_DB: jobplanet_crawler_db
      POSTGRES_USER: jobplanet_crawler_user
      POSTGRES_PASSWORD: jobplanet_crawler_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M # DB에 할당할 최대 메모리

  api:
    image: ghcr.io/hp657/jobplanetcrawler/crawler:latest
    container_name: jobplanet-api-server
    ports:
      - "8080:8080"
    environment:
      # 컨테이너끼리 통신할 때는 내부 포트인 5432 사용
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/jobplanet_crawler_db
      SPRING_DATASOURCE_USERNAME: jobplanet_crawler_user
      SPRING_DATASOURCE_PASSWORD: jobplanet_crawler_password
    depends_on:
      - postgres-db
    restart: always
    deploy:
      resources:
        limits:
          memory: 1024m # 앱에 할당할 최대 메모리 (4GB 중 약 1.5GB만 사용)

volumes:
  postgres_data: